In [1]:
# %pip install numpy==1.26.4  pyyaml

In [2]:
import pandas as pd
import numpy as np
import re
import pyspark

In [3]:
df = pd.read_csv(
    "data/wiki_movie_plots_deduped.csv",
    sep=",",
)

df.head()

,Release Year,Title,Origin/Ethnicity,Director,Cast,Genre,Wiki Page,Plot
0,1901,Kansas Saloon Smashers,American,Unknown,NaN,unknown,https://en.wikipedia.org/wiki/Kansas_Saloon_Sm...,"A bartender is working at a saloon, serving dr..."
1,1901,Love by the Light of the Moon,American,Unknown,NaN,unknown,https://en.wikipedia.org/wiki/Love_by_the_Ligh...,"The moon, painted with a smiling face hangs ov..."
2,1901,The Martyred Presidents,American,Unknown,NaN,unknown,https://en.wikipedia.org/wiki/The_Martyred_Pre...,"The film, just over a minute long, is composed..."
3,1901,"Terrible Teddy, the Grizzly King",American,Unknown,NaN,unknown,"https://en.wikipedia.org/wiki/Terrible_Teddy,_...",Lasting just 61 seconds and consisting of two ...
4,1902,Jack and the Beanstalk,American,"George S. Fleming, Edwin S. Porter",NaN,unknown,https://en.wikipedia.org/wiki/Jack_and_the_Bea...,The earliest known adaptation of the classic f...

In [4]:
missing_percent = df.isnull().mean() * 100
print("\nPercentage of missing data per column:")
print(missing_percent)

Percentage of missing data per column:
Release Year        0.000000
Title               0.000000
Origin/Ethnicity    0.000000
Director            0.000000
Cast                4.076134
Genre               0.000000
Wiki Page           0.000000
Plot                0.000000
dtype: float64

In [5]:
df['Director'] = df['Director'].fillna("Unknown")
df['Cast'] = df['Cast'].fillna("Unknown")
df['Genre'] = df['Genre'].fillna("Unknown")

In [6]:
df.head()

,Release Year,Title,Origin/Ethnicity,Director,Cast,Genre,Wiki Page,Plot
0,1901,Kansas Saloon Smashers,American,Unknown,Unknown,unknown,https://en.wikipedia.org/wiki/Kansas_Saloon_Sm...,"A bartender is working at a saloon, serving dr..."
1,1901,Love by the Light of the Moon,American,Unknown,Unknown,unknown,https://en.wikipedia.org/wiki/Love_by_the_Ligh...,"The moon, painted with a smiling face hangs ov..."
2,1901,The Martyred Presidents,American,Unknown,Unknown,unknown,https://en.wikipedia.org/wiki/The_Martyred_Pre...,"The film, just over a minute long, is composed..."
3,1901,"Terrible Teddy, the Grizzly King",American,Unknown,Unknown,unknown,"https://en.wikipedia.org/wiki/Terrible_Teddy,_...",Lasting just 61 seconds and consisting of two ...
4,1902,Jack and the Beanstalk,American,"George S. Fleming, Edwin S. Porter",Unknown,unknown,https://en.wikipedia.org/wiki/Jack_and_the_Bea...,The earliest known adaptation of the classic f...

In [7]:
df['plot_length'] = df['Plot'].str.len()
print(df['plot_length'].describe())

count    34886.000000
mean      2165.034541
std       1817.325247
min         15.000000
25%        716.000000
50%       1656.000000
75%       3376.000000
max      36773.000000
Name: plot_length, dtype: float64

In [9]:
df_subset = df.sample(frac=0.3, random_state=42)  # 30% of data
df_subset = df_subset.reset_index(drop=True)
print(f'Subset size: {df_subset.shape}')
df_subset.to_csv("data/movie_subset.csv", index=False)

missing_percent = df_subset.isnull().mean() * 100
print("\nPercentage of missing data per column:")
print(missing_percent)

Subset size: (10466, 9)

Percentage of missing data per column:
Release Year        0.0
Title               0.0
Origin/Ethnicity    0.0
Director            0.0
Cast                0.0
Genre               0.0
Wiki Page           0.0
Plot                0.0
plot_length         0.0
dtype: float64